packages:
  - apps/admin
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#f68d9cc092a90a4962dd4c8d46f909033a95c8f0&path:packages/auth-api
