packages:
  - apps/admin
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#46af83a6a7e84183739f25a72548911aaa4204a2&path:packages/auth-api
